# Generated by Django 5.1.6 on 2025-02-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='signature',
            field=models.CharField(default='I am the master of my fate, I am the captain of my soul.', max_length=140),
        ),
    ]
