# Generated by Django 5.1.6 on 2025-02-26 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='publ_date',
            new_name='pub_date',
        ),
    ]
